name: duplicate_payuung_pribadi
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_feather_icons: ^2.0.0+1
  fluentui_system_icons: ^1.1.257

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
